language: python
sudo: false
cache: pip

python:
  - "3.7"

branches:
  only:
    - master

before-install:
  - pip install -U pip wheel

install:
  - pip install --no-cache-dir -U -r requirements.txt

script:
  - ./check_line_length.py
  - openwisp-qa-check --skip-checkmigrations
  - ./runsphinx-build

notifications:
  # will post a summary as a comment on github in case of failure
  webhooks: https://www.travisbuddy.com/
  on_success: never
